baseURL = "https://dssg-berlin.org"
languageCode = "en-us"
title = "DSSG Berlin"
theme = "dssg"

# Site language settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

sectionPagesMenu = "sections"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true